### ISSUE TITLE
Script used to work, doesn't anymore

### ISSUE THREAD

**Issue by deezed420** [terry3041/pyChatGPT#110]
My script doesn't work anymore but it used to flawlessly. Here is the error:
```
Traceback (most recent call last):
  File "c:\Users\Ender\Dev\Homework Solver\main.py", line 9, in <module>
    api = ChatGPT(sessiontoken)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ender\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyChatGPT\pyChatGPT.py", line 125, in __init__
    self.__init_browser()
  File "C:\Users\Ender\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyChatGPT\pyChatGPT.py", line 221, in __init_browser
    self.__ensure_cf()
  File "C:\Users\Ender\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyChatGPT\pyChatGPT.py", line 266, in __ensure_cf
    raise ValueError('Invalid session token')
ValueError: Invalid session token
Exception ignored in: <function ChatGPT.__del__ at 0x000001FD9A447C40>
Traceback (most recent call last):
  File "C:\Users\Ender\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyChatGPT\pyChatGPT.py", line 134, in __del__
    self.driver.quit()
  File "C:\Users\Ender\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 732, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Chrome.__del__ at 0x000001FD9A32B600>
Traceback (most recent call last):
  File "C:\Users\Ender\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 777, in __del__
  File "C:\Users\Ender\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 732, in quit
OSError: [WinError 6] The handle is invalid
```

And here is my script
```
from pyChatGPT import ChatGPT # Import ChatGPT API

# Variables
questions = []
answers = []
sessiontoken = "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..kviLVe3GResUgx2X.72qJyu72n90e1aNbgSkDGnJntiaPOZHKdKPfN3tqpfDDnX_uvY1M9zuCxZNVSYIpJBe8y1N1tK8HWCAvwpKGQsaFTlYdU-EZadSnpvXMWKTgYIQSkJ6qdoVLirKeiyL0XH-nB5LBJQrpELtVAfri5XHnOF35_7lh4llRI2Udiq_L0ywmv1CUtVO9vluBJGJNEZwHllKjyq5bEf-X61mg434nl2ysz08HmLl9jVcKVG9FFiBmEklYBRa-LjVdqhcTyHRLBg2tt0Ouznm4pLD4qxpybc3R5aaghHB5lAXIQZO4jLcvGA7TEXc1StREm3xoNPvKhvO23dnVUgBs1Eq-WwOVIlZPOHw7uHWzmVpMBxPk31-6ACJyetu7h5UrE3ONjBRv2pusljSj3bo1r9VQEL3o1u_UmkZsMsVHmt9Q0NtIviutYsZ8aOvU5E_GX4VSnrSAJb_Y3cnQBrpQoqGGMwkCExhyL5JFM4YL_mas33x1BgAyWtcWZ5VWltBpS4aRUwGGMLAhJ6VDbdc8JWCWLD5MI5BgmXu00KbD1uUXTBL-84TnlixSvof-OzzoLieyvngP_XfoozEWcN3-dsxTDQd9cc_zxLvblDXMwoS8ad2daMVDFzxXpRUcGD-JolUfSZjwAOFpdD5ziIupxhFa4m7ccHc0oFc4eX5hmbfOs0xDB41YDE2MuIK9JuxhetS0jindH1grsMI8tbTS0pVar7khYLOmrCA6OKbgt2_1n4ZsqF7G0F4yCgWIt1Ux3DBX0GQj0Sax2aTl6o8cWLEeAjJZcqYG_NsRWW-TXR_ySE5spN__xqaoV460tDF-SQQWkOO5opUGFyueuf-aVnZszAaapuecW1WY-_4lHzElifMfGPMhvuEZfZbR6Fttra1NAZPrzZVee6Qi93u2MXsDxmcBXo6I4u4xyzI9Nhwl5EASZv1Ow0O6u2WjfAIHttwLr7T71yzLKbgwJcTHQPZiB7E1ZWy16WwucAH97F3muWCkXCXs1gZx06G81Q_L-qbInVOA3ANBNwOqIPyfqwwwF7GWZYOqHsodqjGnZSjq3kNh5H6r4bCwsSmH2YlDYUkOTsXD9cBcfPbIbaffFRvZm-YKle6KcKx1Pz57F7IfOjJnuY5DhMdPB3wbEGufMUr9TAPEtt7rWGUpGCVNPHWAjeSYKz7hQP55o4qhk1Gh38pH-2Qm1T3AHwRLgqxG-5XRfaNM2v02x-1rf0zqMPOwVJzGqWYWzFbrnrJJ7BIVcwd-l8Ru5lPUodixYtA6Tqsru-S-PH1fCxNgW5Du7aPGNJMFiVhuyXYmVvJK7gpQUg9311dDe-TDkg9LQEpkqWU7m-gwhVS2Gbm-e_fdQqGCVFJuFoaYKcF6SYIOTNmmWYFRNZrd9A3G1gOxUlGzrs8g_MMmo7xv4Rc4VMx2ZcVaK0wBnu-odrbFndOltjjtY5nq_vboVe_Twt6fjQGeWhukpmV05EYicoPpOZyUIFKdXBR5UngSRdqtbzaTxA0ABXKUzl6siZf72RTRDCSVEO_3Msm3ZhQBBhhRVg1gvGGqoWY2Z4uBFIMWYHhjtChYFuR3iCvFygHNmFc7iYsgw3HcJTnxP-CYkhDi-CwY_6gKwvq5uHHFDSb_hKNeIwmlYJXEf_OWJhSUV7c1DOlqNy76rvfrmuGWxzmHIR8QjpRaMoStaVsU0D0g8hoW2WdCZsC9rraiJ-n4TfnC5FuG9fw4cgnnUYpvLvBrw2hCe6u-dVeki8T9xaEhLgJMf6x1MlN8Z4W6KxySrmjBDhsZIkGQ1mHIZfcK0Mi6EYWjRhoAVwkiN9RHPiTV-WuiU95h31a9LJ66kKrKOdbYIOod604H7qck6_knR0pevSWI7Lg8SwmuP_loj91xreAD681Hhk8pilSuKbjeP_hJ5uwADRZOvVYOsuBMHC26M3F8d-OZlaio4giv952O3Rz9yaS1qEk8wFe3dfm8ki_0XutxOkWQ3Hs_pZaTYpqykRT7LLwXmZMeUgXGnfQfGuC9c80sC-Bmcdus6pak1Szm0tsP8S3J7e0Gx0s2ib7nQtQPyEUgfVoCR5j1OHQSxbXKpxT4bN9UQE6DN3f9i9bi4_ra0nR4HsjK4dga1YjIREY6vAELSi2H5WMvE3vXB2SxrNv0jTmtFjuzKGYdqUjuiBLea-smON5vGC54Itv89N4no86vUal4BnwhrMgFs1U6iipsRz4D05t_Aw6aR9gdBoOWH7nhlV1XtsCkN3_aAkfI9ASlV3A0PCdogMYWXXEM9qXe_2NR3DH0uZryMSM.mYZFcjtgsPOf1Ny0RZ3JTA"

# Start the api
api = ChatGPT(sessiontoken)

# Read questions
with open("./questions.txt", "r") as f: questions += f.readlines()

# Send query to api
for q in questions: response = api.send_message(q) ; answers.append(response["message"])

# Clean up answers list
answers = [a[:-1] for a in answers]

# Write answers to file
with open("./answers.txt", "w") as f: f.write(''.join(answers))

# Close chrome window
api.clear_conversations()
api.driver.close()
```

Please help

**Comment by terry3041** [comment]
session_token expired.
