### ISSUE TITLE
ndexError: list index out of range

### ISSUE THREAD

**Issue by 10kkm** [terry3041/pyChatGPT#118]
Traceback (most recent call last):
  File "D:\chatgpt\main.py", line 8, in <module>
    resp = api.send_message(ga)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyChatGPT\pyChatGPT.py", line 444, in send_message
    response = self.driver.find_elements(*chatgpt_small_response)[-1]
IndexError: list index out of range

**Comment by JewishLewish** [comment]
+1
