### ISSUE TITLE
new auth:  <Verify you are human> .Can not login. 

### ISSUE THREAD

**Issue by HelloWorldWinning** [terry3041/pyChatGPT#123]
cloudflare has new auth:  <Verify you are human> .
api can not log anymore.
error: Cloudflare authorized error.

**Comment by peteh** [comment]
Can confirm, same for me. Even with clicking manually it does not let me pass.

**Comment by brmi1** [comment]
I also have this problem on Windows 10 if I set **chrome_args=['--headless']**. **Python 3.8.5**, **pip 23.0**

```
Traceback (most recent call last):
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 244, in __ensure_cf        
    WebDriverWait(self.driver, 10).until_not(
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 113, in until_not
    raise TimeoutException(message)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 244, in __ensure_cf        
    WebDriverWait(self.driver, 10).until_not(
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 113, in until_not
    raise TimeoutException(message)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 244, in __ensure_cf        
    WebDriverWait(self.driver, 10).until_not(
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 113, in until_not
    raise TimeoutException(message)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 244, in __ensure_cf        
    WebDriverWait(self.driver, 10).until_not(
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 113, in until_not
    raise TimeoutException(message)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Roman/Desktop/main.py", line 4, in <module>
    api = ChatGPT(session_token, chrome_args=['--headless'])
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 126, in __init__
    self.__init_browser()
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 223, in __init_browser     
    self.__ensure_cf()
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 254, in __ensure_cf        
    return self.__ensure_cf(retry - 1)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 254, in __ensure_cf        
    return self.__ensure_cf(retry - 1)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 254, in __ensure_cf        
    return self.__ensure_cf(retry - 1)
  File "C:\Users\Roman\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 255, in __ensure_cf        
    raise ValueError('Cloudflare challenge failed')
ValueError: Cloudflare challenge failed
```
