### ISSUE TITLE
help：list index out of range

### ISSUE THREAD

**Issue by different-ouvivid** [terry3041/pyChatGPT#154]
Traceback (most recent call last):
File "D:\chatgpt\main.py", line 8, in
resp = api.send_message(ga)
File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pyChatGPT\pyChatGPT.py", line 444, in send_message
response = self.driver.find_elements(*chatgpt_small_response)[-1]
IndexError: list index out of range

**Comment by different-ouvivid** [comment]
remember to install :pip install ffmpeg_downloader PyPasser pocketsphinx   and  pip install pyvirtualdisplay

**Comment by DevWand** [comment]
not fix
