### ISSUE TITLE
do not work

### ISSUE THREAD

**Issue by elcarim** [terry3041/pyChatGPT#158]
(venv) PS W:\py\chatgpt> & w:/py/chatgpt/venv/Scripts/python.exe w:/py/chatgpt/pychatpgt.py
Traceback (most recent call last):
  File "w:\py\chatgpt\pychatpgt.py", line 36, in <module>
    resp = api.send_message('Hello, world!')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\py\chatgpt\venv\Lib\site-packages\pyChatGPT\pyChatGPT.py", line 414, in send_message
    textbox.click()
  File "W:\py\chatgpt\venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "W:\py\chatgpt\venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\py\chatgpt\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "W:\py\chatgpt\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <textarea id="prompt-textarea" tabindex
="0" data-id="8a965664-bfe2-4aba-8707-cfd9b4fd08c3" rows="1" placeholder="Send a message" class="m-0 w-full resize-none border-0 bg-transparent
p-0 pr-10 focus:ring-0 focus-visible:ring-0 dark:bg-transparent md:pr-12 pl-3 md:pl-0" style="max-height: 200px; height: 24px; overflow-y: hidde
n;"></textarea> is not clickable at point (1090, 905). Other element would receive the click: <div class="grid-cols-[10px_1fr_10px] grid h-full
w-full grid-rows-[minmax(10px,_1fr)_auto_minmax(10px,_1fr)] md:grid-rows-[minmax(20px,_1fr)_auto_minmax(20px,_1fr)] overflow-y-auto">...</div>
  (Session info: chrome=116.0.5845.141)
Stacktrace:
        GetHandleVerifier [0x010A37C3+48947]
        (No symbol) [0x01038551]
        (No symbol) [0x00F3C92D]
        (No symbol) [0x00F6E276]
        (No symbol) [0x00F6CF4D]
        (No symbol) [0x00F6B74B]
        (No symbol) [0x00F6ABA5]
        (No symbol) [0x00F63420]
        (No symbol) [0x00F8508C]
        (No symbol) [0x00F62EB6]
        (No symbol) [0x00F853E4]
        (No symbol) [0x00F975DA]
        (No symbol) [0x00F84E86]
        (No symbol) [0x00F616C7]
        (No symbol) [0x00F6284D]
        GetHandleVerifier [0x012EFDF9+2458985]
        GetHandleVerifier [0x0133744F+2751423]
        GetHandleVerifier [0x01331361+2726609]
        GetHandleVerifier [0x01120680+560624]
        (No symbol) [0x0104238C]
        (No symbol) [0x0103E268]
        (No symbol) [0x0103E392]
        (No symbol) [0x010310B7]
        BaseThreadInitThunk [0x76E005C9+25]
        RtlGetAppContainerNamedObjectPath [0x76FB77AD+237]
        RtlGetAppContainerNamedObjectPath [0x76FB777D+189]

**Comment by shubhp2610** [comment]
+1 Same error

**Comment by AM9988** [comment]
It still works but you need to change some lines in the pychatgpt file. Open AI are watching this so we cannot post the solution neither the contributor

**Comment by Niez-Gharbi** [comment]
+1 same error, any solutions ?
