### ISSUE TITLE
session deleted because of page crash

### ISSUE THREAD

**Issue by helloxz** [terry3041/pyChatGPT#17]
I run on linux and install chromium-browser and xvfb, but there is an error:

```
Traceback (most recent call last):
  File "1.py", line 7, in <module>
    resp = api1.send_message('hello')
  File "/usr/local/lib/python3.8/site-packages/pyChatGPT/pyChatGPT.py", line 151, in send_message
    self.__ensure_cf()
  File "/usr/local/lib/python3.8/site-packages/pyChatGPT/pyChatGPT.py", line 113, in __ensure_cf
    self.driver.switch_to.new_window('tab')
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/switch_to.py", line 108, in new_window
    value = self._driver.execute(Command.NEW_WINDOW, {"type": type_hint})["value"]
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=108.0.5359.94)
Stacktrace:
```

**Comment by terry3041** [comment]
This seems to be related to memory issues from https://stackoverflow.com/a/53970825.
Can you type `df -h` in the terminal and show your output?
