### ISSUE TITLE
Chrome tab is staying open

### ISSUE THREAD

**Issue by ShadowTimGit** [terry3041/pyChatGPT#31]
Was working pretty well for a while, but started to get an error with it only taking one message before saying i was sending too many requests per hour as an error. Realized there was a new version available and assuming it was just openai patching a previous use, so updated to latest version, and now it seems to work fine but the chrome browser tab ChatGPT(TOKEN) uses is staying open on my screen instead of running in the background. Is this new behavior intentional?

**Comment by terry3041** [comment]
Well for now its intended because headless environment does not support minimizing the browser window.
So I have to keep compatibility. And its my exam period right now. I dont have the time to maintain this currently.

**Comment by mancunian1792** [comment]
You can get the driver object and close it yourself in your use case. 

ChatGPT_object_instance.driver.close() should do it.

**Comment by kimkimkeren** [comment]
Well, somehow here I get error when closing the window
```
PS D:\openai-twitter-bot> python.exe script.py
Exception ignored in: <function ChatGPT.__del__ at 0x0000026F1896FDC0>
Traceback (most recent call last):
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 94, in __del__
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\__init__.py", line 721, in quit
AttributeError: 'NoneType' object has no attribute 'debug'
PS D:\openai-twitter-bot>
```
I guess it's related to importing error on chromedriver library part

**Comment by terry3041** [comment]
> AttributeError: 'NoneType' object has no attribute 'debug'

Did you quit the driver manually (i.e. `driver.quit()`)?
You don't need to do that in newer version.

**Comment by kimkimkeren** [comment]
> Did you quit the driver manually (i.e. `driver.quit()`)? You don't need to do that in newer version.

No I don't, the traceback said the error comes from pychatgpt code

**Comment by kimkimkeren** [comment]
After a few days, I saw the window didn't quit automatically after executing the script. After seeing the main library, I use __del__ function and it seems work

**Comment by terry3041** [comment]
> After a few days, I saw the window didn't quit automatically after executing the script. After seeing the main library, I use `__del__` function and it seems work

Can you please try the latest version. It should quit the browser automatically now. Thanks.
