### ISSUE TITLE
 api1.reset_conversation() crashes de app

### ISSUE THREAD

**Issue by alcarazolabs** [terry3041/pyChatGPT#35]
Hi dear I'm [fighting] with this library to be able to connect me to chatgpt.
The example code works in my case without   `api1.reset_conversation()` but this only works
one time in the second time when I send another question to chatgpt the app crashes.

I'm testing it by using ubuntu 
```

Traceback (most recent call last):
  File "/home/freddy/Documents/aws-projects/chatgptproject/process.py", line 155, in <module>
    mqttClient.loop_forever()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/dist-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/freddy/Documents/aws-projects/chatgptproject/process.py", line 148, in on_message
    transcribe_file(JOB_NAME, file_uri, transcribe_client)
  File "/home/freddy/Documents/aws-projects/chatgptproject/process.py", line 82, in transcribe_file
    sendToChatGPT(text)
  File "/home/freddy/Documents/aws-projects/chatgptproject/process.py", line 115, in sendToChatGPT
    api1.reset_conversation()  # reset the conversation - Se comenta por que genera crashes.
  File "/usr/local/lib/python3.10/dist-packages/pyChatGPT/pyChatGPT.py", line 416, in reset_conversation
    self.driver.find_element(By.LINK_TEXT, 'New Thread').click()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"New Thread"}
  (Session info: chrome=108.0.5359.98)
Stacktrace:
#0 0x563bb34472a3 <unknown>
#1 0x563bb3205f77 <unknown>
#2 0x563bb324280c <unknown>
#3 0x563bb3242a71 <unknown>
#4 0x563bb327c734 <unknown>
#5 0x563bb3262b5d <unknown>
#6 0x563bb327a47c <unknown>
#7 0x563bb3262903 <unknown>
#8 0x563bb3235ece <unknown>
#9 0x563bb3236fde <unknown>
#10 0x563bb349763e <unknown>
#11 0x563bb349ab79 <unknown>
#12 0x563bb347d89e <unknown>
#13 0x563bb349ba83 <unknown>
#14 0x563bb3470505 <unknown>
#15 0x563bb34bcca8 <unknown>
#16 0x563bb34bce36 <unknown>
#17 0x563bb34d8333 <unknown>
#18 0x7f6845670b43 <unknown>
```

I repeat my code only works one time commeting this line of code `api1.reset_conversation()` . If I uncoment it the application will get crash.

I hope a sooner solution.
thanks.

**Comment by terry3041** [comment]
Just release v0.3.9.3. Check and see if it works.

**Comment by alcarazolabs** [comment]
> Just release v0.3.9.3. Check and see if it works.

Thanks, I updated now, however I'm getting this error:

```
Traceback (most recent call last):
  File "/home/freddy/Documents/aws-projects/chatgptproject/chatgpt.py", line 9, in <module>
    api1.reset_conversation()  # reset the conversation 
  File "/usr/local/lib/python3.10/dist-packages/pyChatGPT/pyChatGPT.py", line 416, in reset_conversation
    self.driver.find_element(By.LINK_TEXT, 'New Chat').click()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"New Chat"}
  (Session info: chrome=108.0.5359.98)
Stacktrace:
#0 0x55c0e35a82a3 <unknown>
#1 0x55c0e3366f77 <unknown>
#2 0x55c0e33a380c <unknown>
#3 0x55c0e33a3a71 <unknown>
#4 0x55c0e33dd734 <unknown>
#5 0x55c0e33c3b5d <unknown>
#6 0x55c0e33db47c <unknown>
#7 0x55c0e33c3903 <unknown>
#8 0x55c0e3396ece <unknown>
#9 0x55c0e3397fde <unknown>
#10 0x55c0e35f863e <unknown>
#11 0x55c0e35fbb79 <unknown>
#12 0x55c0e35de89e <unknown>
#13 0x55c0e35fca83 <unknown>
#14 0x55c0e35d1505 <unknown>
#15 0x55c0e361dca8 <unknown>
#16 0x55c0e361de36 <unknown>
#17 0x55c0e3639333 <unknown>
#18 0x7f390bbd5b43 <unknown>
```


Code:

```
from pyChatGPT import ChatGPT
session_token = 'XXX'
api1 = ChatGPT(session_token)  # auth with session token

resp = api1.send_message("Me puedes dar un resumen de lo que es la ecologia?")
print(resp['message'])

api1.reset_conversation()

resp = api1.send_message("Me puedes dar un resumen de lo que es la psicologia?")
print(resp['message'])

api1.reset_conversation()

api1.close()  # close the session
    
```
```
La ecología también incluye el estudio de cómo los humanos afectan al medio ambiente y cómo las actividades humanas pueden tener impactos a largo plazo en los ecosistemas y los organismos que los habitan. Esta disciplina es importante porque nos proporciona información sobre cómo proteger y conservar los ecosistemas y sus recursos, y nos ayuda a comprender cómo nuestras acciones pueden tener efectos en el mundo natural.


Traceback (most recent call last):
  File "/home/freddy/Documents/aws-projects/chatgptproject/chatgpt.py", line 9, in <module>
    api1.reset_conversation()  # reset the conversation - Se comenta por que genera crashes.
  File "/usr/local/lib/python3.10/dist-packages/pyChatGPT/pyChatGPT.py", line 416, in reset_conversation
    self.driver.find_element(By.LINK_TEXT, 'New Chat').click()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"New Chat"}
  (Session info: chrome=108.0.5359.98)
Stacktrace:
#0 0x55c0e35a82a3 <unknown>
#1 0x55c0e3366f77 <unknown>
#2 0x55c0e33a380c <unknown>
#3 0x55c0e33a3a71 <unknown>
#4 0x55c0e33dd734 <unknown>
#5 0x55c0e33c3b5d <unknown>
#6 0x55c0e33db47c <unknown>
#7 0x55c0e33c3903 <unknown>
#8 0x55c0e3396ece <unknown>
#9 0x55c0e3397fde <unknown>
#10 0x55c0e35f863e <unknown>
#11 0x55c0e35fbb79 <unknown>
#12 0x55c0e35de89e <unknown>
#13 0x55c0e35fca83 <unknown>
#14 0x55c0e35d1505 <unknown>
#15 0x55c0e361dca8 <unknown>
#16 0x55c0e361de36 <unknown>
#17 0x55c0e3639333 <unknown>
#18 0x7f390bbd5b43 <unknown>
```
It only retrieves the first question then when it do reset conversation it got crash.
