### ISSUE TITLE
urllib error

### ISSUE THREAD

**Issue by kimkimkeren** [terry3041/pyChatGPT#39]
```
Traceback (most recent call last):
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 88, in <module>
    api = pyChatGPT(session_token)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 68, in __init__
    self.__init_browser()
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\site-packages\pyChatGPT\pyChatGPT.py", line 110, in __init_browser
    self.driver = uc.Chrome(options=options, enable_cdp_events=True)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\__init__.py", line 242, in __init__
    patcher.auto()
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
    release = self.fetch_release_number()
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\site-packages\undetected_chromedriver\patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Lukmanul Hakim\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

**Comment by benfir123** [comment]
Ran into the same issue. You can solve it by installing the "Install Certificates.command"
See this thread: https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
Hope that helps!
