### ISSUE TITLE
If the first answer by GPT is error,  can't found "//div[starts-with(@class, 'markdown prose break-words')]"

### ISSUE THREAD

**Issue by 872226263** [terry3041/pyChatGPT#46]
Traceback (most recent call last):
  File "D:/research/pyChatGPT/run.py", line 24, in <module>
    resp = api.send_message(question)
  File "C:\develop_tools\Anaconda\envs\ChatGPT\lib\site-packages\pyChatGPT\pyChatGPT.py", line 395, in send_message
    response = self.driver.find_elements(
KeyboardInterrupt

**Comment by 872226263** [comment]
I change the code,

**Comment by scaryama** [comment]
My solve is modify 'pyChatGPT.py' file
"//div[starts-with(@Class, 'markdown prose break-words')]"
↓
"//div[starts-with(@class, 'markdown prose w-full break-words')]"

**Comment by terry3041** [comment]
Should be fixed in v0.3.9.5.
