### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

### ISSUE THREAD

**Issue by zjrwtx** [terry3041/pyChatGPT#47]
Traceback (most recent call last):
  File "D:\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "D:\python\lib\http\client.py", line 975, in send
    self.connect()
  File "D:\python\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "D:\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\python\lib\site-packages\pyChatGPT\__main__.py", line 12, in <module>
    chat = ChatGPT(session_token)
  File "D:\python\lib\site-packages\pyChatGPT\pyChatGPT.py", line 70, in __init__
    self.__init_browser()
  File "D:\python\lib\site-packages\pyChatGPT\pyChatGPT.py", line 112, in __init_browser
    self.driver = uc.Chrome(options=options, enable_cdp_events=True)
  File "D:\python\lib\site-packages\undetected_chromedriver\__init__.py", line 242, in __init__
    patcher.auto()
  File "D:\python\lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
    release = self.fetch_release_number()
  File "D:\python\lib\site-packages\undetected_chromedriver\patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
  File "D:\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

**Comment by zjrwtx** [comment]
how to  solve it?

**Comment by DevRoss** [comment]
The possible reason is that the network is not stable or the OpenAI does not support the country, try to use proxy.

**Comment by zjrwtx** [comment]
> The possible reason is that the network is not stable or the OpenAI does not support the country, try to use proxy.

i have solve it , thanks
