### ISSUE TITLE
session token is str，but still met TypeError

### ISSUE THREAD

**Issue by JingxinLee** [terry3041/pyChatGPT#8]
session_token = 'eyJh....1y'
Why I set session_token str, but still met the TypeError?
```
Traceback (most recent call last):
  File "/home/ubuntu/work/chatgpt.py", line 8, in <module>
    api = ChatGPT(session_token)  # auth with session token
  File "/home/ubuntu/anaconda3/envs/chatgpt/lib/python3.9/site-packages/pyChatGPT/pyChatGPT.py", line 57, in __init__
    self.driver = uc.Chrome(options=options)
  File "/home/ubuntu/anaconda3/envs/chatgpt/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    browser = subprocess.Popen(
  File "/home/ubuntu/anaconda3/envs/chatgpt/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/ubuntu/anaconda3/envs/chatgpt/lib/python3.9/subprocess.py", line 1696, in _execute_child
    and os.path.dirname(executable)
  File "/home/ubuntu/anaconda3/envs/chatgpt/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by terry3041** [comment]
Hi. This library requires a Google Chrome installation since version `v0.2.0`. Have you installed Chrome?
I have also updated the library for a better error handling when utilising Chrome.

**Comment by thuSunao** [comment]
> Hi. This library requires a Google Chrome installation since version v0.2.0. Have you installed Chrome? I have also updated the library for a better error handling when utilising Chrome.

I have installed Chrome, and i saw my chrome started and opened the website, but still got the wrong response which looked like a html file, how can i fix it?

**Comment by terry3041** [comment]
> I have installed Chrome, and i saw my chrome started and opened the website, but still got the wrong response which looked like a html file, how can i fix it?

Can you provide a detailed log? Make sure to censor sensitive information.

**Comment by JingxinLee** [comment]
> 

I am using Ubuntu. You mean I should install chrome  (https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb) first?

**Comment by terry3041** [comment]
> > 
> 
> I am using Ubuntu. You mean I should install chrome (https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb) first?

Yes.

**Comment by JingxinLee** [comment]
When I use **api2 = ChatGPT(email="xxx@gmail.com", password="yyy")**   I got this error.

```
Traceback (most recent call last):
  File "C:\Users\Jingxin Li\Desktop\data\chatgpt.py", line 9, in <module>
    api2 = ChatGPT(
  File "D:\study\envs\chatgpt\lib\site-packages\pychatgpt\pyChatGPT.py", line 70, in __init__
    self.session_token = self.__login(email, password)
  File "D:\study\envs\chatgpt\lib\site-packages\pychatgpt\pyChatGPT.py", line 206, in __login
    raise ValueError(f'Could not get session token: {cookies}')
ValueError: Could not get session token:
```

**Comment by JingxinLee** [comment]
When I use api2 = ChatGPT(email="xxx@gmail.com", password="yyy") I got this error.

```
Traceback (most recent call last):
  File "C:\Users\Li\Desktop\data\chatgpt.py", line 9, in <module>
    api2 = ChatGPT(
  File "D:\study\envs\chatgpt\lib\site-packages\pychatgpt\pyChatGPT.py", line 70, in __init__
    self.session_token = self.__login(email, password)
  File "D:\study\envs\chatgpt\lib\site-packages\pychatgpt\pyChatGPT.py", line 206, in __login
    raise ValueError(f'Could not get session token: {cookies}')
ValueError: Could not get session token:
```

**Comment by terry3041** [comment]
> When I use api2 = ChatGPT(email="[xxx@gmail.com](mailto:xxx@gmail.com)", password="yyy") I got this error.

Auth with login credentials is a bit unreliable. I am finding fix at the moment.
By the meantime, can you please use `session_token` as a replacement?

**Comment by terry3041** [comment]
> When I use api2 = ChatGPT(email="[xxx@gmail.com](mailto:xxx@gmail.com)", password="yyy") I got this error.

Another reason you are unable to get a "session_token" is that you are not in a supported region of OpenAI.

**Comment by terry3041** [comment]
Added a more detailed error handling for this error in v0.2.5. Please check and let me know if you have any questions.
